"""Catalog generator for RoboCasa365 (family ``robocasa``); network only when invoked.

The official RoboCasa365 datasets (``robocasa/scripts/download_datasets.py``) are one
uncompressed ``lerobot.tar`` per task, split and source, served as Box shared files
(``robocasa/models/assets/box_links/box_links_ds.json`` at the pinned RoboCasa commit).
Each tar holds a LeRobot v2.1 dataset: ``data/`` (per-episode parquet), ``meta/``,
``extras/`` (``dataset_meta.json``; per episode ``ep_meta.json``, ``model.xml.gz`` = the
recorded MJCF, ``states.npz`` = MuJoCo states) and ``videos/`` (MP4). Every tar becomes a
``tar_stream`` entry pinned by Box file id, file version and SHA-1 plus size (Box publishes
no SHA-256); MimicGen tars (``/mg/``) get ``usable: false`` (no simulator extras in the
inspected sample) and their human seed dataset. Asset archives are ``file`` entries
(``content: assets``): HF ``robocasa/robocasa-assets`` zips (LFS SHA-256), Box-only zips
(SHA-256 computed from a stream whose size and Box SHA-1 matched), the GitHub source zip of
the commit and the robosuite wheel (PyPI digest)::

    python -m reachy_retarget.acquire.generators.robocasa --commit <sha> --asset-revision <sha>
"""
from __future__ import annotations

import argparse
import hashlib
import json
import posixpath
import re
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

import yaml

from ..fetch import ChecksumMismatch
from ..transports import ResumingStream, default_opener, make_request

FAMILY = "robocasa"
ROBOCASA_REPO = "https://github.com/robocasa/robocasa"
ASSET_REPO = "robocasa/robocasa-assets"
ASSET_MARKER = "robocasa/models/assets/"
HEADER = """\
# Pinned RoboCasa365 files. Generated by reachy_retarget.acquire.generators.robocasa from publisher metadata
# (RoboCasa dataset registry and Box link tables at the pinned commit, Box file metadata, HF LFS sha256, PyPI
# digests); edit by regenerating, not by hand. kind: file = asset archives (content: assets); kind: tar_stream =
# the per-task LeRobot tars on Box: they embed MP4 videos, are streamed and verified whole (size + Box sha1; Box
# publishes no sha256) and only non-image members are stored. MimicGen tars (source: mg) checked so far carry no
# extras/ (no MJCF, no MuJoCo states): only parquet robot observations/actions, so they are usable: false.
# kind = how bytes are acquired (file | file_images_embedded | tar_stream | range_member | range_package; all
# through reachy_retarget.acquire.fetch); content = what they are (low_dim | metadata | assets | docs | index ...).
"""


def zip_marker(name: str) -> str:
    """Recorded-path fragment after which a reference equals the asset zip's member name.

    Object zips (``objaverse/``, ``aigen_objs/``, ``lightwheel/`` members) are unpacked
    by RoboCasa into ``models/assets/objects/``, the others into ``models/assets/``.
    """
    stem = posixpath.basename(name).removesuffix(".zip")
    return ASSET_MARKER + ("objects/" if stem in ("objaverse", "aigen_objs", "objects_lightwheel") else "")


def _get(url, opener, headers=None) -> bytes:
    req = make_request(url)
    for k, v in (headers or {}).items():
        req.add_header(k, v)
    with opener(req) as r:
        return r.read()


def box_metadata(shared_link, opener=None) -> dict:
    """File id, version id, SHA-1, name and size of a public Box shared file (page scrape)."""
    html = _get(shared_link, opener or default_opener).decode("utf-8", "replace")
    m = re.search(r'"preview_metadata":\{"type":"file","id":"(\d+)".*?"sha1":"([0-9a-f]{40})","file_version":'
                  r'\{"type":"file_version","id":"(\d+)","sha1":"([0-9a-f]{40})"\},"name":"([^"]*)","size":(\d+)', html)
    if not m:
        raise ValueError(f"{shared_link}: no Box file metadata found")
    return {"box_file_id": m[1], "box_sha1": m[2], "box_file_version": m[3], "name": m[5], "size": int(m[6])}


def static_url(shared_link: str, ext: str) -> str:
    """``https://utexas.box.com/s/<id>`` -> ``https://utexas.box.com/shared/static/<id>.<ext>``."""
    return f"{shared_link.split('/s/')[0]}/shared/static/{shared_link.rstrip('/').rsplit('/', 1)[1]}.{ext}"


def parse_registry(text: str) -> dict:
    """``{tar key: (task, variant, horizon)}`` from ``robocasa/utils/dataset_registry.py``."""
    out = {}
    for block in re.finditer(r"\n    (\w+)=dict\((.*?)\n    \),", text, re.S):
        task, body = block[1], block[2]
        hz = re.search(r"horizon=(\d+)", body)
        for var, p in re.findall(r'(\w+_path)="(v1\.0/[^"]+)"', body):
            out[p.split("v1.0/", 1)[1].rstrip("/") + "/lerobot.tar"] = (task, var, int(hz[1]) if hz else None)
    return out


def tar_rows(registry: dict, links_ds: dict, metas: dict) -> list[dict]:
    """``tar_stream`` rows from the registry, the Box link table and Box metadata."""
    humans = {(t, k.split("/")[0]): f"robocasa/v1.0/{posixpath.dirname(k)}"
              for k, (t, var, _) in registry.items() if var == "human_path"}
    rows = []
    for key, link in sorted(links_ds.items()):
        md = metas[key]
        split, task_type, task = key.split("/")[:3]
        reg = registry.get(key)
        variant = reg[1] if reg else ("mg_path" if "/mg/" in key else "human_path")
        source = "mg" if "/mg/" in key else "human"
        path = f"v1.0/{key}"
        seed, note = None, None
        if source == "mg":
            seed = f"robocasa/v1.0/{key.split('/mg/')[0]}"
            human = humans.get((task, split))
            if human and human != seed:
                note = (f"MimicGen folder is not under its task's human dataset; seed taken from the registry's "
                        f"human_path ({human}), the source demos may be an earlier collection")
                seed = human
        row = dict(path=path, url=static_url(link, "tar"), size=md["size"], sha1=md["box_sha1"], content="low_dim",
                   dataset=f"robocasa/{posixpath.dirname(path)}", usable=False if source == "mg" else None,
                   task=task, split=split, task_type=task_type, source=source,
                   variant=variant if reg else f"{variant} (not in registry)", shared_link=link,
                   box_file_id=md["box_file_id"], box_file_version=md["box_file_version"], seed=seed,
                   horizon=reg[2] if reg else None, note=note)
        rows.append({k: v for k, v in row.items() if v is not None})
    return rows


def generate_catalog(out_path, *, commit, asset_revision, robosuite_version="1.5.2", opener=None,
                     workers=8) -> dict:
    """Rebuild ``robocasa.yaml`` from publisher metadata (network; explicit call only)."""
    opener = opener or default_opener
    raw = f"https://raw.githubusercontent.com/robocasa/robocasa/{commit}/robocasa"
    registry = parse_registry(_get(f"{raw}/utils/dataset_registry.py", opener).decode())
    links_ds = json.loads(_get(f"{raw}/models/assets/box_links/box_links_ds.json", opener))
    links_assets = json.loads(_get(f"{raw}/models/assets/box_links/box_links_assets.json", opener))
    with ThreadPoolExecutor(workers) as ex:
        metas = dict(zip(links_ds, ex.map(lambda v: box_metadata(v, opener), links_ds.values())))
    tars = tar_rows(registry, links_ds, metas)
    hf = json.loads(_get(f"https://huggingface.co/api/datasets/{ASSET_REPO}/tree/{asset_revision}", opener))
    hf_files = [{"path": f"assets/{f['path']}", "url": f"https://huggingface.co/datasets/{ASSET_REPO}/resolve/"
                 f"{asset_revision}/{f['path']}", "sha256": f["lfs"]["oid"], "size": f["size"], "kind": "file",
                 "content": "assets", "asset_marker": zip_marker(f["path"])}
                for f in hf if f["path"].endswith(".zip")]
    hf_names = {posixpath.basename(f["path"]) for f in hf_files}
    box_files = []
    for name, link in sorted(links_assets.items()):
        if f"{name}.zip" in hf_names:
            continue
        md = box_metadata(link, opener)
        stream = ResumingStream(static_url(link, "zip"), opener)
        try:
            stream.drain()
        finally:
            stream.close()
        if stream.pos != md["size"] or stream.sha1.hexdigest() != md["box_sha1"]:
            raise ChecksumMismatch(f"{name}.zip: streamed bytes do not match Box size/sha1")
        box_files.append({"path": f"assets/{name}.zip", "url": static_url(link, "zip"),
                          "sha256": stream.sha256.hexdigest(), "size": md["size"], "kind": "file", "content": "assets",
                          "asset_marker": zip_marker(f"{name}.zip"), "sha1": md["box_sha1"],
                          "note": f"Box file {md['box_file_id']} version {md['box_file_version']} sha1 "
                                  f"{md['box_sha1']}; sha256 computed at catalog time from a stream whose size "
                                  "and sha1 matched Box (Box publishes no SHA-256)"})
    code = _get(f"https://codeload.github.com/robocasa/robocasa/zip/{commit}", opener)
    pypi = json.loads(_get(f"https://pypi.org/pypi/robosuite/{robosuite_version}/json", opener))
    whl = next(u for u in pypi["urls"] if u["filename"].endswith("-py3-none-any.whl"))
    doc = {"sources": [
        {"family": FAMILY, "repo": f"https://huggingface.co/datasets/{ASSET_REPO}", "revision": asset_revision,
         "license": "CC-BY-4.0", "files": hf_files},
        {"family": FAMILY, "repo": "box_links_assets.json", "revision": commit, "license": "CC-BY-4.0",
         "files": box_files},
        {"family": FAMILY, "repo": ROBOCASA_REPO, "revision": commit, "license": "MIT",
         "files": [{"path": f"robocasa-{commit}.zip", "url": f"https://codeload.github.com/robocasa/robocasa/zip/{commit}",
                    "sha256": hashlib.sha256(code).hexdigest(), "size": len(code), "kind": "file", "content": "assets",
                    "asset_marker": ASSET_MARKER,
                    "note": "GitHub source archive; digest computed at catalog time (GitHub publishes none). "
                            "Code MIT; the models/assets tree inside is CC-BY-4.0 (README)."}]},
        {"family": "robosuite", "repo": "https://pypi.org/project/robosuite/", "revision": robosuite_version,
         "license": "MIT", "files": [{"path": whl["filename"], "url": whl["url"], "sha256": whl["digests"]["sha256"],
                                      "size": whl["size"], "kind": "file", "content": "assets",
                                      "asset_marker": "robosuite/models/assets/"}]},
        {"family": FAMILY, "repo": f"{ROBOCASA_REPO} (box_links_ds.json)", "revision": commit, "license": "CC-BY-4.0",
         "kind": "tar_stream", "note": "Per task/split/source LeRobot tars on Box; see the header.",
         "files": tars}],
        "registry_without_download": sorted(f"v1.0/{k}" for k in registry if k not in links_ds)}
    Path(out_path).write_text(HEADER + yaml.safe_dump(doc, sort_keys=False, width=120))
    return doc


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--commit", required=True)
    ap.add_argument("--asset-revision", required=True)
    ap.add_argument("--robosuite-version", default="1.5.2")
    ap.add_argument("--out", required=True)
    a = ap.parse_args(argv)
    generate_catalog(a.out, commit=a.commit, asset_revision=a.asset_revision, robosuite_version=a.robosuite_version)


if __name__ == "__main__":
    main()


__all__ = ["box_metadata", "generate_catalog", "parse_registry", "static_url", "tar_rows", "zip_marker"]
