"""Adapter for MolmoBot-Data trajectory files (``allenai/molmobot-data``).

Each ``trajectories_batch_<i>_of_<n>.h5`` holds ``traj_<k>`` groups generated by the
MolmoBot planner in MolmoSpaces (MuJoCo) houses on two robots:

* ``franka_droid``: Franka FR3 + Robotiq 2F-85 on a fixed pedestal (``Franka*`` configs);
* ``rby1m``: Rainbow RB-Y1M, holonomic base + 6-DoF torso + two 7-DoF arms with parallel
  grippers (``RBY1*`` and ``DoorOpening`` configs).

What the files contain (verified on every catalogued package, see docs/sources.md):
per-step robot joint state (``obs/agent/qpos``, JSON by move group), commanded actions,
robot base pose, recorded TCP poses, per-step success, task info, and the frozen
generation config (initial poses of all scene objects, task object names, goals).
**Per-step object poses are not stored** (``env_states`` only has the robot). Object
tracks are therefore measured only at ``t = 0`` (``valid[0]``); door handles (from
``door_state``) and the opened joint of open tasks (``task_info.joint_position``) are
measured at every step. :func:`rigid_grasp_track` derives a pick-object track under a
rigid-grasp assumption; it is not part of the episode.

Effector poses come from forward kinematics of the pinned MolmoSpaces robot models
(see ``catalog/molmobot.yaml``), verified per trajectory against the recorded TCP poses
(``provenance["fk_check"]``). The grasp-center frame is measured from the model
geometry with the fingers open, as in the robosuite adapter: origin = midpoint of the
two finger contact faces, +z = palm -> that midpoint (approach), +y = finger-1 face ->
finger-2 face (closing). Nothing is simulated or stepped.
"""
from __future__ import annotations

import base64
import hashlib
import io
import json
import pickle
import posixpath
import re
import xml.etree.ElementTree as ET
import zipfile
from functools import lru_cache
from pathlib import Path

import h5py
import numpy as np

from ..schema.source import Articulation, Effector, ObjectTrack, SourceEpisode
from .registry import register

# ---------------------------------------------------------------- robot specifications

ROBOTS = {
    "rby1m": {
        "xml": "rby1_v1.2_site_control.xml",
        "catalog_id": "molmobot/molmospaces/mujoco/robots/rby1m/20251224/shards/00000.tar",
        "version": "20251224",
        "groups": {
            "base": ["base_x", "base_y", "base_theta"],
            "torso": [f"torso_{i}" for i in range(6)],
            "left_arm": [f"left_arm_{i}" for i in range(7)],
            "right_arm": [f"right_arm_{i}" for i in range(7)],
            "left_gripper": ["gripper_finger_l1", "gripper_finger_l2"],
            "right_gripper": ["gripper_finger_r1", "gripper_finger_r2"],
            "head": ["head_0", "head_1"],
        },
        "prefix": "robot_0/",
        "effectors": {
            "left": {"site": "ee_site_l", "fingers": ["gripper_finger_l1", "gripper_finger_l2"],
                     "pads": ["ee_finger_l1", "ee_finger_l2"], "side": "left",
                     "tcp_keys": ["left_tcp_pose", "tcp_pose"]},
            "right": {"site": "ee_site_r", "fingers": ["gripper_finger_r1", "gripper_finger_r2"],
                      "pads": ["ee_finger_r1", "ee_finger_r2"], "side": "right",
                      "tcp_keys": ["right_tcp_pose"]},
        },
        "torso_body": "link_torso_5",
        "license": "unknown (no LICENSE file in the MolmoSpaces rby1m package)",
    },
    "franka_droid": {
        "xml": "model.xml",
        "catalog_id": "molmobot/molmospaces/mujoco/robots/franka_droid/20260127/shards/00000.tar",
        "version": "20260127",
        "groups": {
            "arm": [f"fr3_joint{i}" for i in range(1, 8)],
            # Robotiq 2F-85: the recorded values are the two driver joints; spring links
            # and followers are closed-chain joints equal to the driver (checked at load).
            "gripper": ["gripper/left_driver_joint", "gripper/right_driver_joint"],
        },
        "coupled": {"gripper/left_driver_joint": ["gripper/left_spring_link_joint", "gripper/left_follower"],
                    "gripper/right_driver_joint": ["gripper/right_spring_link_joint", "gripper/right_follower_joint"]},
        "prefix": "",
        "effectors": {
            "gripper": {"site": "gripper/grasp_site", "fingers": ["gripper/left_driver_joint", "gripper/right_driver_joint"],
                        "pads": ["gripper/left_pad", "gripper/right_pad"], "side": None,
                        "tcp_keys": ["tcp_pose"]},
        },
        "base_link": "fr3_link0",
        "license": "Apache-2.0 (FR3) AND BSD-3-Clause (Robotiq 2F-85)",
    },
}

ROLE_BY_TASK = {"pick": {}, "pick_and_place": {"receptacle": "receptacle"},
                "pick_and_place_color": {"receptacle": "receptacle"},
                "pick_and_place_next_to": {"receptacle": "fixture"}}
FK_TOL_M = 0.002          # 99th-percentile gates for FK vs recorded TCP (float32 storage)
FK_TOL_RAD = 2e-3


# ---------------------------------------------------------------- safe config decoding

_NUMPY_OK = {("numpy._core.multiarray", "_reconstruct"), ("numpy.core.multiarray", "_reconstruct"),
             ("numpy", "ndarray"), ("numpy", "dtype"), ("numpy._core.multiarray", "scalar"),
             ("numpy.core.multiarray", "scalar"), ("pathlib", "PosixPath"), ("pathlib", "PurePosixPath")}


class _Stub:
    _qualname = ""

    def __init__(self, *args, **kwargs):
        pass

    def __setstate__(self, state):
        self.__dict__["_state"] = state


class _ConfigUnpickler(pickle.Unpickler):
    """Only numpy array/scalar reconstruction and paths; every other class becomes an inert stub."""

    def find_class(self, module, name):
        if (module, name) in _NUMPY_OK:
            import importlib
            return getattr(importlib.import_module(module), name)
        return type(name, (_Stub,), {"_qualname": f"{module}.{name}"})


def _plain(o):
    if isinstance(o, _Stub):
        st = o.__dict__.get("_state") or {}
        if isinstance(st, tuple):
            st = next((s for s in st if isinstance(s, dict)), {})
        if "__dict__" in st:
            st = st["__dict__"]
        return {"__class__": o._qualname, **{k: _plain(v) for k, v in st.items() if not k.startswith("__pydantic")}}
    if isinstance(o, dict):
        return {str(k): _plain(v) for k, v in o.items()}
    if isinstance(o, (list, tuple)):
        return [_plain(v) for v in o]
    if isinstance(o, np.ndarray):
        return o.tolist()
    if isinstance(o, np.generic):
        return o.item()
    if hasattr(o, "__fspath__"):
        return str(o)
    return o


def decode_config(encoded: str) -> dict:
    """Decode ``obs_scene["frozen_config"]`` (base64 pickle) into plain dicts without running code."""
    return _plain(_ConfigUnpickler(io.BytesIO(base64.b64decode(encoded))).load())


def _json_rows(ds) -> list:
    return [json.loads(bytes(r).rstrip(b"\x00").decode()) for r in ds[()]]


# ---------------------------------------------------------------- robot model files

class RobotFiles:
    """Read-only view of a robot asset tree (directory or zip archive)."""

    def __init__(self, path, subdir: str = ""):
        self.path, self.subdir = Path(path), subdir.strip("/")
        base = self.path / self.subdir if self.subdir else self.path
        if self.path.is_dir():
            self.names = {p.relative_to(base).as_posix() for p in base.rglob("*") if p.is_file()}
            self._zip = None
        else:
            self._zip = zipfile.ZipFile(self.path)
            pre = f"{self.subdir}/" if self.subdir else ""
            self.names = {n[len(pre):] for n in self._zip.namelist() if n.startswith(pre) and not n.endswith("/")}

    def read(self, rel: str) -> bytes | None:
        rel = posixpath.normpath(rel)
        if rel not in self.names:
            return None
        full = f"{self.subdir}/{rel}" if self.subdir else rel
        return self._zip.read(full) if self._zip else (self.path / full).read_bytes()

    def manifest(self) -> dict | None:
        data = self.read("MANIFEST.json")
        return json.loads(data) if data else None


def compile_robot_xml(files: RobotFiles, main: str):
    """Flatten ``<include>``, resolve asset paths and sub-models for ``MjModel.from_xml_string``.

    Returns ``(xml, assets, missing)``. Missing mesh files become 1 mm spheres and
    missing textures are dropped: body/site/joint kinematics stay exact, geometry does not.
    """
    assets, missing = {}, []

    def load(rel):
        data = files.read(rel)
        if data is None:
            raise FileNotFoundError(f"{files.path}: {rel}")
        root = ET.fromstring(data)
        base = posixpath.dirname(rel)
        comp = root.find("compiler")
        dirs = {"mesh": "", "texture": "", "hfield": "", "skin": ""}
        if comp is not None:
            md = comp.attrib.pop("meshdir", "")
            td = comp.attrib.pop("texturedir", "")
            ad = comp.attrib.pop("assetdir", "")
            dirs = {"mesh": md or ad, "texture": td or ad, "hfield": ad, "skin": md or ad}
        _inline(root, base)
        dropped = set()
        for el in root.iter():
            if el.tag in dirs and el.get("file"):
                f = posixpath.normpath(posixpath.join(base, dirs[el.tag], el.get("file")))
                data = files.read(f)
                if data is None:
                    missing.append(f)
                    dropped.add((el.tag, el.get("name") or posixpath.splitext(posixpath.basename(f))[0]))
                    el.set("file", "")
                else:
                    assets[f] = data
                    el.set("file", f)
            elif el.tag == "model" and el.get("file"):
                f = posixpath.normpath(posixpath.join(base, el.get("file")))
                assets[f] = load(f).encode()
                el.set("file", f)
        _placeholders(root, dropped)
        return ET.tostring(root, encoding="unicode")

    def _inline(node, base):
        for i, ch in enumerate(list(node)):
            if ch.tag == "include":
                inc = posixpath.normpath(posixpath.join(base, ch.get("file")))
                data = files.read(inc)
                if data is None:
                    raise FileNotFoundError(f"{files.path}: include {inc}")
                sub = ET.fromstring(data)
                ibase = posixpath.dirname(inc)
                for el in sub.iter():  # paths inside an included file are relative to it
                    if el.tag in ("mesh", "texture", "hfield", "skin") and el.get("file"):
                        el.set("file", posixpath.relpath(posixpath.join(ibase, el.get("file")), base or "."))
                _inline(sub, base)
                pos = list(node).index(ch)
                node.remove(ch)
                for k, s in enumerate(list(sub)):
                    node.insert(pos + k, s)
            else:
                _inline(ch, base)

    def _placeholders(root, dropped):
        if not dropped:
            return
        meshes = {n for t, n in dropped if t == "mesh"}
        textures = {n for t, n in dropped if t == "texture"}
        for parent in root.iter():
            for el in list(parent):
                if el.tag in ("mesh", "texture") and el.get("file") == "":
                    parent.remove(el)
        for mat in root.iter("material"):
            if mat.get("texture") in textures:
                mat.attrib.pop("texture")
        for geom in root.iter("geom"):
            if geom.get("mesh") in meshes:
                geom.attrib.pop("mesh")
                geom.set("type", "sphere")
                geom.set("size", "0.001")

    xml = load(main)
    return xml, assets, missing


class RobotModel:
    """Compiled source robot with FK helpers and gripper geometry measured once."""

    def __init__(self, name: str, files: RobotFiles):
        import mujoco

        spec = ROBOTS[name]
        self.mj, self.name, self.spec, self.files = mujoco, name, spec, files
        self.xml, self.assets, self.missing = compile_robot_xml(files, spec["xml"])
        self.m = mujoco.MjModel.from_xml_string(self.xml, self.assets)
        self.d = mujoco.MjData(self.m)
        p = spec["prefix"]
        jid = lambda n: self.m.joint(p + n).id
        self.groups = {g: self.m.jnt_qposadr[[jid(n) for n in names]] for g, names in spec["groups"].items()}
        self.coupled = {self.m.jnt_qposadr[jid(k)]: self.m.jnt_qposadr[[jid(n) for n in v]]
                        for k, v in spec.get("coupled", {}).items()}
        self._check_coupling()
        self.grippers = {k: _Gripper(self, k, e) for k, e in spec["effectors"].items()}
        self.torso = self.m.body(p + spec["torso_body"]).id if "torso_body" in spec else None
        self.base_link = self.m.body(p + spec["base_link"]).id if "base_link" in spec else None
        self.base_body = self.m.body(p + "base").id if name == "rby1m" else None

    def _check_coupling(self):
        """The closed-chain Robotiq joints follow the driver (connect residual < 1e-5 m)."""
        mj, m, d = self.mj, self.m, self.d
        if not self.coupled:
            return
        for a in (0.2, 0.5, 0.8):
            d.qpos[:] = m.qpos0
            for drv, rest in self.coupled.items():
                d.qpos[drv] = a
                d.qpos[rest] = a
            mj.mj_forward(m, d)
            res = [abs(d.efc_pos[i]) for i in range(d.nefc) if d.efc_type[i] == mj.mjtConstraint.mjCNSTR_EQUALITY]
            if res and max(res) > 1e-5:
                raise ValueError(f"{self.name}: coupled gripper joints violate the closed chain ({max(res):.2e} m)")

    def set_groups(self, q: dict):
        d = self.d
        d.qpos[:] = self.m.qpos0
        for g, adr in self.groups.items():
            vals = q.get(g)
            if vals is None or len(vals) == 0:
                continue
            d.qpos[adr] = vals
        for drv, rest in self.coupled.items():
            d.qpos[rest] = d.qpos[drv]
        self.mj.mj_kinematics(self.m, d)

    def describe(self) -> dict:
        man = self.files.manifest() or {}
        return {"name": self.name, "xml": self.spec["xml"], "files": str(self.files.path),
                "catalog_id": man.get("catalog_id", self.spec["catalog_id"]), "shard_sha256": man.get("shard_sha256"),
                "xml_sha256": hashlib.sha256(self.files.read(self.spec["xml"])).hexdigest(),
                "missing_assets": len(self.missing), "license": self.spec["license"],
                "effectors": {k: g.describe() for k, g in self.grippers.items()}}


class _Gripper:
    """Two-finger gripper; contact faces measured from collision geometry with fingers open."""

    def __init__(self, robot: RobotModel, key: str, spec: dict):
        mj, m, d = robot.mj, robot.m, robot.d
        p = robot.spec["prefix"]
        self.key, self.site = key, m.site(p + spec["site"]).id
        self.side = spec["side"]
        self.tcp_keys = spec["tcp_keys"]
        self.fingers = [m.joint(p + n).id for n in spec["fingers"]]
        self.adr = m.jnt_qposadr[self.fingers]
        self.pad_bodies = [m.body(p + n).id for n in spec["pads"]]
        rng = m.jnt_range[self.fingers]
        # Open/closed limits per finger joint: the limit giving the larger contact-face
        # separation is "open" (measured, not assumed; RB-Y1 fingers open at -0.05/+0.05,
        # Robotiq drivers at 0).
        q = m.qpos0[self.adr].copy()
        for j in range(len(self.fingers)):
            seps = []
            for lim in rng[j]:
                qq = q.copy()
                qq[j] = lim
                seps.append(self._measure(robot, qq)[3])
            q[j] = rng[j][int(np.argmax(seps))]
        self.q_open = q
        self.q_closed = np.array([r[0] if o == r[1] else r[1] for o, r in zip(q, rng)])
        Rs, ps, c_body, sep_open, palm = self._measure(robot, self.q_open, keep=True)
        self.pad_local = c_body                       # contact-face centre in each pad body frame
        p1, p2 = self._pads_world(d)
        mid = (p1 + p2) / 2
        z = Rs.T @ (mid - palm)
        z /= np.linalg.norm(z)
        y = Rs.T @ (p2 - p1)
        y -= z * (y @ z)
        y /= np.linalg.norm(y)
        fix = np.column_stack([np.cross(y, z), y, z])
        snapped = np.round(fix)
        self.raw_fix = fix
        ok = np.abs(fix - snapped).max() < np.sin(np.radians(3)) and abs(np.linalg.det(snapped) - 1) < 1e-9
        self.R_fix = snapped if ok else fix
        self.offset = Rs.T @ (mid - ps)
        self.sep_open = sep_open
        # Width is the physical gap between the contact faces (clipped at 0); at the
        # closed joint limit the faces touch (RB-Y1, 0.2 mm) or overlap (Robotiq, -8.6 mm).
        self.gap_at_closed_limit = self._measure(robot, self.q_closed, axis_site=self.axis_site)[3]
        self.width_max = self.sep_open

    def _pads_world(self, d):
        return [d.xpos[b] + d.xmat[b].reshape(3, 3) @ c for b, c in zip(self.pad_bodies, self.pad_local)]

    def _measure(self, robot, q, keep=False, axis_site=None):
        """Contact-face centres: collision points within 1 mm of the innermost point along the finger axis.

        The finger-1 -> finger-2 axis comes from the finger centroids unless ``axis_site``
        (fixed in the site frame, measured at the open pose) is given.
        """
        mj, m, d = robot.mj, robot.m, robot.d
        robot.set_groups({})
        d.qpos[self.adr] = q
        for drv, rest in robot.coupled.items():
            d.qpos[rest] = d.qpos[drv]
        mj.mj_kinematics(m, d)
        pts = [self._collision_points(robot, b) for b in self.pad_bodies]
        Rs = d.site_xmat[self.site].reshape(3, 3)
        if axis_site is None:
            c1, c2 = pts[0].mean(0), pts[1].mean(0)
            axis = (c2 - c1) / np.linalg.norm(c2 - c1)
        else:
            axis = Rs @ axis_site
        if keep:
            self.axis_site = Rs.T @ axis
        faces = []
        for k, P in enumerate(pts):
            s = P @ axis * (1 if k == 0 else -1)          # larger = closer to the other finger
            faces.append(P[s >= s.max() - 1e-3])
        centres = [(F.min(0) + F.max(0)) / 2 for F in faces]
        sep = (centres[1] - centres[0]) @ axis
        if not keep:
            return None, None, None, sep, None
        body_local = [d.xmat[b].reshape(3, 3).T @ (c - d.xpos[b]) for b, c in zip(self.pad_bodies, centres)]
        palm = d.xpos[m.body_parentid[m.jnt_bodyid[self.fingers[0]]]].copy()
        return d.site_xmat[self.site].reshape(3, 3).copy(), d.site_xpos[self.site].copy(), body_local, sep, palm

    @staticmethod
    def _collision_points(robot, body):
        mj, m, d = robot.mj, robot.m, robot.d
        out = []
        sub = [b for b in range(m.nbody) if _in_subtree(m, b, body)]
        for g in range(m.ngeom):
            if m.geom_bodyid[g] not in sub or not (m.geom_contype[g] or m.geom_conaffinity[g]):
                continue
            R, c = d.geom_xmat[g].reshape(3, 3), d.geom_xpos[g]
            if m.geom_type[g] == mj.mjtGeom.mjGEOM_MESH:
                mid = m.geom_dataid[g]
                v = m.mesh_vert[m.mesh_vertadr[mid]:m.mesh_vertadr[mid] + m.mesh_vertnum[mid]]
            elif m.geom_type[g] == mj.mjtGeom.mjGEOM_BOX:
                v = m.geom_size[g] * np.array([[x, y, z] for x in (-1, 1) for y in (-1, 1) for z in (-1, 1)])
            else:
                continue  # placeholders and primitives without a contact face
            out.append(c + v @ R.T)
        if not out:
            raise ValueError(f"{robot.name}: no collision geometry under finger body {body} (finger meshes missing?)")
        return np.concatenate(out)

    def read(self, d) -> tuple[np.ndarray, float]:
        Rs = d.site_xmat[self.site].reshape(3, 3)
        T = np.eye(4)
        T[:3, :3] = Rs @ self.R_fix
        T[:3, 3] = d.site_xpos[self.site] + Rs @ self.offset
        p1, p2 = self._pads_world(d)
        return T, max(0.0, float((p2 - p1) @ T[:3, 1]))

    def site_pose(self, d) -> np.ndarray:
        T = np.eye(4)
        T[:3, :3] = d.site_xmat[self.site].reshape(3, 3)
        T[:3, 3] = d.site_xpos[self.site]
        return T

    def describe(self) -> dict:
        return {"site_to_contract_rotation": self.R_fix.round(6).tolist(),
                "unsnapped_rotation": self.raw_fix.round(6).tolist(),
                "grasp_center_in_site_frame_m": self.offset.round(6).tolist(),
                "finger_q_open": np.round(self.q_open, 6).tolist(), "finger_q_closed": np.round(self.q_closed, 6).tolist(),
                "width_max_m": round(float(self.width_max), 6),
                "face_gap_at_closed_limit_m": round(float(self.gap_at_closed_limit), 6)}


def _in_subtree(m, b, root):
    while b > 0 and b != root:
        b = m.body_parentid[b]
    return b == root


@lru_cache(maxsize=4)
def _robot(name: str, path: str, subdir: str = "") -> RobotModel:
    return RobotModel(name, RobotFiles(path, subdir))


def _robot_source(name: str, path: Path, root, robot_assets) -> tuple[str, str]:
    """``(path, subdir)`` of the robot asset tree; a zip may hold ``<name>/`` folders."""
    if robot_assets and name in robot_assets:
        p = Path(robot_assets[name])
        if p.is_file() and zipfile.is_zipfile(p):
            with zipfile.ZipFile(p) as z:
                sub = name if any(n.startswith(f"{name}/") for n in z.namelist()) else ""
            return str(p), sub
        return str(p), ""
    return str(_locate_robot(name, path, root)), ""


def _locate_robot(name: str, path: Path, root) -> Path:
    if root is None:
        root = next((p.parent for p in path.resolve().parents if p.name == "raw"), None)
    spec = ROBOTS[name]
    if root is not None:
        d = Path(root) / "raw" / "molmobot" / "robots" / name / spec["version"]
        if d.exists():
            return d
    raise FileNotFoundError(f"robot assets for {name!r} not found; fetch {spec['catalog_id']} and run "
                            "molmobot_fetch.unpack_robot_assets, or pass robot_assets={name: dir_or_zip}")


# ---------------------------------------------------------------- geometry helpers

def _quat_mat(q):
    w, x, y, z = q
    return np.array([[1 - 2 * (y * y + z * z), 2 * (x * y - w * z), 2 * (x * z + w * y)],
                     [2 * (x * y + w * z), 1 - 2 * (x * x + z * z), 2 * (y * z - w * x)],
                     [2 * (x * z - w * y), 2 * (y * z + w * x), 1 - 2 * (x * x + y * y)]])


def _mat_quat(R):
    import mujoco
    q = np.zeros(4)
    mujoco.mju_mat2Quat(q, np.asarray(R, float).reshape(9))
    return q


def _pose7_T(p):
    T = np.eye(4)
    T[:3, :3] = _quat_mat(np.asarray(p[3:7], float) / np.linalg.norm(p[3:7]))
    T[:3, 3] = p[:3]
    return T


def _rot_angle(Ra, Rb) -> float:
    """Angle of Ra^T Rb, accurate for small angles."""
    E = Ra.T @ Rb
    v = np.array([E[2, 1] - E[1, 2], E[0, 2] - E[2, 0], E[1, 0] - E[0, 1]]) / 2
    return float(np.arctan2(np.linalg.norm(v), (np.trace(E) - 1) / 2))


def _yaw_quat(yaw):
    return np.array([np.cos(yaw / 2), 0.0, 0.0, np.sin(yaw / 2)])


def _t0_track(pose7, T: int, role: str, geometry: dict) -> ObjectTrack:
    pose = np.tile(np.asarray(pose7, float), (T, 1))
    valid = np.zeros(T, bool)
    valid[0] = True
    return ObjectTrack(pose=pose, valid=valid, role=role, geometry={**geometry, "measured_rows": "t0 only"})


# ---------------------------------------------------------------- adapter

def _member_info(path: Path, packages):
    try:
        from .molmobot_fetch import find_package
        return find_package(path, packages)
    except Exception:  # noqa: BLE001 - catalog lookup is optional provenance
        return None, None


def _layout(path: Path):
    """``(config, split, part, house)`` from ``.../<config>/<split>/part<k>/<house>/<file>`` when present."""
    parts = path.resolve().parts
    if len(parts) >= 5 and re.fullmatch(r"part\d+", parts[-3]):
        return parts[-5], parts[-4], int(parts[-3][4:]), parts[-2]
    return None, None, None, path.parent.name


@register("molmobot")
def read_molmobot_h5(path: Path, *, family: str, trajs=None, root=None, robot_assets=None, packages=None):
    """Yield one :class:`SourceEpisode` per ``traj_<k>`` of a MolmoBot trajectory file.

    ``robot_assets`` maps a robot name (``rby1m``/``franka_droid``) to an unpacked asset
    directory or zip; by default ``<root>/raw/molmobot/robots/<name>/<version>`` is used,
    with ``root`` inferred from ``path`` when it lies under a ``raw/`` folder.
    """
    path = Path(path)
    digest = hashlib.sha256(path.read_bytes()).hexdigest()
    pkg, member = _member_info(path, packages)
    config, split, part, house = _layout(path)
    if pkg is not None:
        config, split, part = pkg.config, pkg.split, pkg.part
    batch = re.search(r"batch_(\d+)_of_(\d+)", path.name)
    with h5py.File(path, "r") as f:
        keys = sorted((k for k in f if k.startswith("traj_")), key=lambda k: int(k[5:]))
        if trajs is not None:
            keys = [k for k in keys if k in set(trajs)]
        mask = f["valid_traj_mask"][()].tolist() if "valid_traj_mask" in f else None
        for key in keys:
            yield _episode(f[key], key, path, digest, pkg, member, config, split, part, house, batch, mask,
                           family, root, robot_assets)


def _episode(g, key, path, digest, pkg, member, config, split, part, house, batch, mask, family,
             root, robot_assets):
    scene = json.loads(g["obs_scene"][()].decode())
    cfg = decode_config(scene["frozen_config"])
    rc, tc = cfg["robot_config"], cfg["task_config"]
    rname = rc["name"]
    if rname not in ROBOTS or Path(rc["robot_xml_path"]).name != ROBOTS[rname]["xml"]:
        raise ValueError(f"{path}:{key}: unsupported robot {rname!r} ({rc['robot_xml_path']})")
    robot = _robot(rname, *_robot_source(rname, path, root, robot_assets))
    d = robot.d
    qpos = _json_rows(g["obs/agent/qpos"])
    T = len(qpos)
    extra = g["obs/extra"]
    dt = float(scene["policy_dt_ms"]) / 1000.0
    time = np.arange(T) * dt

    # World frame of the robot's model frame.
    base_pose = np.asarray(extra["robot_base_pose"][()], float)        # (T, 7) x y z wxyz, world
    if rname == "franka_droid":
        h = float((rc.get("base_size") or [0, 0, 0])[2])
        world_from_model = _pose7_T(base_pose[0]) @ _trans(0, 0, h)     # model origin = fr3_link0
    else:
        world_from_model = np.eye(4)                                     # base joints are world x, y, yaw

    poses = {k: np.zeros((T, 4, 4)) for k in robot.grippers}
    widths = {k: np.zeros(T) for k in robot.grippers}
    torso_z = np.zeros(T) if robot.torso is not None else None
    base = np.zeros((T, 3)) if rname == "rby1m" else None
    fk_err = {}
    for t in range(T):
        robot.set_groups(qpos[t])
        for k, gr in robot.grippers.items():
            P, w = gr.read(d)
            poses[k][t], widths[k][t] = world_from_model @ P, w
            # Recorded TCP poses are expressed in the robot base frame on the floor (RB-Y1:
            # x, y, yaw of the base; Franka: the pedestal frame robot_base_pose).
            for tk in gr.tcp_keys:
                if tk in extra and len(extra[tk].shape) == 2:
                    ref = _pose7_T(base_pose[t]) if rname == "franka_droid" else \
                        _trans(*qpos[t]["base"][:2], 0.0) @ _rotz(qpos[t]["base"][2])
                    S = np.linalg.inv(ref) @ world_from_model @ gr.site_pose(d)
                    rec = np.asarray(extra[tk][t], float)
                    e_p = float(np.linalg.norm(S[:3, 3] - rec[:3]))
                    e_r = _rot_angle(S[:3, :3], _quat_mat(rec[3:] / np.linalg.norm(rec[3:])))
                    a = fk_err.setdefault(k, {"key": tk, "pos": [], "rot": []})
                    a["pos"].append(e_p)
                    a["rot"].append(e_r)
                    break
        if torso_z is not None:
            torso_z[t] = (world_from_model @ np.r_[d.xpos[robot.torso], 1.0])[2]
        if base is not None:
            base[t] = qpos[t]["base"][:3]
    if base is not None:
        base[:, 2] = np.unwrap(base[:, 2])
    for k, v in fk_err.items():
        pe, re_ = np.asarray(v.pop("pos")), np.asarray(v.pop("rot"))
        v.update({"pos_median_m": float(np.median(pe)), "pos_p99_m": float(np.percentile(pe, 99)),
                  "pos_max_m": float(pe.max()), "rot_median_rad": float(np.median(re_)),
                  "rot_p99_rad": float(np.percentile(re_, 99)), "rot_max_rad": float(re_.max())})
        # Isolated larger rotation residuals coincide with large joint steps (recording skew
        # between qpos and the TCP observation), so the gate uses the 99th percentile.
        v["ok"] = v["pos_p99_m"] <= FK_TOL_M and v["rot_p99_rad"] <= FK_TOL_RAD

    effectors = {k: Effector(pose=poses[k], width=widths[k],
                             opening=np.clip(widths[k] / robot.grippers[k].width_max, 0.0, 1.0),
                             side_hint=robot.grippers[k].side) for k in robot.grippers}

    task_type = scene.get("task_type")
    objects, articulations, derived_notes = {}, {}, []
    pickup = tc.get("pickup_obj_name")
    if task_type in ("pick", "pick_and_place", "pick_and_place_color", "pick_and_place_next_to") and pickup:
        start = tc.get("pickup_obj_start_pose") or extra["obj_start"][0].tolist()
        objects[pickup] = _t0_track(start, T, "manipulated", {"body": pickup})
        rec_name = tc.get("place_receptacle_name") or scene.get("place_receptacle_name")
        rec_pose = tc.get("place_receptacle_start_pose")
        if rec_name and rec_pose is not None:
            role = ROLE_BY_TASK.get(task_type, {}).get("receptacle", "receptacle")
            objects[rec_name] = _t0_track(rec_pose, T, role, {"body": rec_name})
    task_info = _json_rows(extra["task_info"])
    if task_type == "door_open" and "door_state" in extra:
        ds = _json_rows(extra["door_state"])
        hinge = np.asarray([s["door_position"] for s in ds], float)
        handle = np.asarray([s["handle_position"] for s in ds], float)
        yaw = np.arctan2(handle[:, 1] - hinge[:, 1], handle[:, 0] - hinge[:, 0])
        door = tc.get("door_body_name") or "door"
        articulations[door] = Articulation(joint_names=[f"{door}:hinge"],
                                           qpos=np.asarray([s["joint_angle"][0] for s in ds], float)[:, None])
        objects[f"{door}:handle"] = ObjectTrack(
            pose=np.column_stack([handle, np.stack([_yaw_quat(y) for y in yaw])]), valid=np.ones(T, bool),
            role="manipulated",
            geometry={"body": door, "kind": "door_handle", "handle_extents_m": ds[0].get("handle_extents"),
                      "hinge_position": hinge[0].round(6).tolist(),
                      "orientation": "derived: +x = hinge -> handle direction in the horizontal plane"})
        derived_notes.append("door handle orientation derived from hinge->handle direction")
    elif task_type == "open" and tc.get("joint_name"):
        jp = np.asarray([ti.get("joint_position", np.nan) for ti in task_info], float)
        art = pickup or "articulated_object"
        articulations[art] = Articulation(joint_names=[tc["joint_name"]], qpos=jp[:, None])
        if tc.get("pickup_obj_start_pose") is not None:
            objects[art] = _t0_track(tc["pickup_obj_start_pose"], T, "fixture", {"body": art})

    success_rows = np.asarray(g["success"][()], bool)
    grasp = {}
    for gk in [k for k in extra if k.startswith("grasp_state_")]:
        rows = _json_rows(extra[gk])
        grasp[gk[len("grasp_state_"):]] = {h: {"held": [bool(r[h]["held"]) for r in rows],
                                               "touching": [bool(r[h]["touching"]) for r in rows]} for h in rows[0]}
    traj_idx = int(key[5:])
    valid_traj = None if mask is None or traj_idx >= len(mask) else bool(mask[traj_idx])
    dataset = f"molmobot/{config}/{split}" if config else f"{family}/{path.parent.name}"
    ep_id = "/".join(x for x in (f"part{part}" if part is not None else None, house,
                                 f"batch_{batch.group(1)}_of_{batch.group(2)}" if batch else path.stem, key) if x)
    provenance = {
        "file": str(path), "sha256": digest, "traj_key": key,
        "catalog_package": pkg.id if pkg else None, "package_range_sha256": pkg.range_sha256 if pkg else None,
        "shard": pkg.shard if pkg else None, "shard_sha256": pkg.shard_sha256 if pkg else None,
        "url": pkg.url if pkg else None, "revision": pkg.revision if pkg else None,
        "config": config, "split": split, "part": part, "house": house,
        "scene_family": pkg.scene_family if pkg else None,
        "commercial_valid_episodes": pkg.commercial_valid_episodes if pkg else None,
        "valid_traj": valid_traj, "task_type": task_type, "task_class": cfg.get("task_cls_str"),
        "policy_dt_s": dt, "time_source": "step index * policy_dt_ms (no simulator clock recorded)",
        "robot": robot.describe(), "robot_config": {k: rc.get(k) for k in ("name", "robot_xml_path", "base_size",
                                                                          "default_world_pose", "command_mode")},
        "frame": ("RB-Y1M model frame = world (base joints are world x, y, yaw; robot root 5 mm above the floor)"
                  if rname == "rby1m" else
                  "world_from_fr3_link0 = robot_base_pose * translate(0, 0, base_size[2])"),
        "fk_check": fk_err,
        "torso_height": "world z of link_torso_5 (arm and neck mount)" if torso_z is not None else None,
        "base_yaw": "unwrapped" if base is not None else None,
        "base_hint_source": "robot_base_pose (pedestal frame on the support surface)" if rname == "franka_droid" else None,
        "object_state": ("not recorded per step: object tracks are valid at t0 only (initial pose from the frozen "
                         "config); see rigid_grasp_track for a derived estimate"),
        "derived": derived_notes,
        "pickup_obj_goal_pose": tc.get("pickup_obj_goal_pose"),
        "final_task_info": task_info[-1] if task_info else None,
        "grasp_state": grasp,
        "referral_expressions": scene.get("referral_expressions"),
        "scene_initial_object_poses": tc.get("object_poses"),
        "added_objects": tc.get("added_objects"),
        "success_source": "success[-1] (per-step environment success flag at the final step)",
        "first_success_step": int(np.argmax(success_rows)) if success_rows.any() else None,
        "scene_ref": ("None: the MolmoSpaces house scene (scene_family/house) and its objects are published in "
                      "allenai/molmospaces but are not catalogued or assembled yet"),
    }
    base_hint = None
    if rname == "franka_droid":
        R = _quat_mat(base_pose[0, 3:] / np.linalg.norm(base_pose[0, 3:]))
        base_hint = np.array([base_pose[0, 0], base_pose[0, 1], np.arctan2(R[1, 0], R[0, 0])])
    return SourceEpisode(
        family=family, dataset=dataset, episode_id=ep_id, task=task_type or config or "unknown", time=time,
        effectors=effectors, objects=objects, base=base, base_hint=base_hint, torso_height=torso_z,
        articulations=articulations, scene=None, instruction=scene.get("task_description"),
        success=bool(success_rows[-1]) if len(success_rows) else None,
        regime="mobile_manipulation" if rname == "rby1m" else "tabletop",
        license=(pkg.license if pkg else "ODC-BY-1.0"), provenance=provenance,
        lineage={"generated": False, "synthetic": True, "generator": "MolmoBot planner data generation (MolmoSpaces)",
                 "seed": None})


def _trans(x, y, z):
    T = np.eye(4)
    T[:3, 3] = (x, y, z)
    return T


def _rotz(a):
    T = np.eye(4)
    c, s = np.cos(a), np.sin(a)
    T[:2, :2] = [[c, -s], [s, c]]
    return T


# ---------------------------------------------------------------- derived (not stored)

def rigid_grasp_track(ep: SourceEpisode, obj: str, effector: str | None = None) -> ObjectTrack:
    """Estimate a pick-object track from its t0 pose and the recorded grasp flags.

    Assumptions (a derived label, never stored in episodes): the object rests at its t0
    pose until the first ``held`` or ``touching`` step; during the longest contiguous
    ``held`` run it is rigidly attached to the grasp center with the relative pose of
    the run's first step. Rows between first contact and that run, and after the run,
    are invalid. RB-Y1 files never set ``held`` (verified on the catalogued subset), so
    this only works for the Franka configs.
    """
    track = ep.objects[obj]
    gs = ep.provenance.get("grasp_state", {}).get("pickup_obj", {})
    if not gs:
        raise ValueError("no grasp_state_pickup_obj in this episode")
    key = effector or next(iter(ep.effectors))
    hand = {"gripper": "gripper", "left": "left_gripper", "right": "right_gripper"}[key]
    held = np.asarray(gs[hand]["held"], bool)
    contact = held | np.asarray(gs[hand]["touching"], bool)
    if not held.any():
        raise ValueError(f"{hand} never holds {obj}; held flags are unusable for this episode")
    T = ep.length
    edges = np.flatnonzero(np.diff(np.r_[0, held.astype(int), 0]))
    runs = list(zip(edges[::2], edges[1::2]))
    s, r = max(runs, key=lambda ab: ab[1] - ab[0])
    pose = np.tile(track.pose[0], (T, 1))
    valid = np.zeros(T, bool)
    valid[:int(np.argmax(contact))] = True
    E = ep.effectors[key].pose
    W0 = _pose7_T(track.pose[0])
    if not contact[:s].any():
        valid[:s] = True
    rel = np.linalg.inv(E[s]) @ W0
    for t in range(s, r):
        W = E[t] @ rel
        pose[t] = np.r_[W[:3, 3], _mat_quat(W[:3, :3])]
        valid[t] = True
    return ObjectTrack(pose=pose, valid=valid, role=track.role,
                       geometry={**track.geometry, "derived": "rigid attachment during the longest held run",
                                 "held_rows": [int(s), int(r)]})


__all__ = ["read_molmobot_h5", "decode_config", "compile_robot_xml", "RobotFiles", "RobotModel", "ROBOTS",
           "rigid_grasp_track"]
